# Generated by Django 4.1.7 on 2023-07-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website_link', models.CharField(max_length=200)),
                ('book_title_path', models.CharField(max_length=200)),
                ('chapter_title_path', models.CharField(max_length=200)),
                ('pager_path', models.CharField(max_length=200)),
                ('next_book_page_link_path', models.CharField(max_length=200)),
                ('previous_book_page_link_path', models.CharField(max_length=200)),
                ('book_title_page_length', models.CharField(max_length=200)),
                ('art_path', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(verbose_name='create time')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_link', models.CharField(max_length=200)),
                ('last_page_link', models.CharField(max_length=200)),
                ('art_link', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(verbose_name='create time')),
                ('last_call_time', models.DateTimeField(verbose_name='last call time')),
                ('Website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryJ.website')),
            ],
        ),
    ]
