# Generated by Django 4.1.7 on 2023-07-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryJ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='pager_path',
            new_name='content_path',
        ),
    ]
