# Generated by Django 4.1.7 on 2023-07-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryJ', '0003_alter_book_create_time_alter_book_last_call_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='book_title_page_link_supplement',
            field=models.CharField(default='', max_length=200),
        ),
    ]
