# Generated by Django 4.1.7 on 2023-07-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryJ', '0004_website_book_title_page_link_supplement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='website_link',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
