# Generated by Django 4.1.7 on 2023-07-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryJ', '0005_alter_website_name_alter_website_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='book_title_page_length',
            field=models.IntegerField(),
        ),
    ]
