# Generated by Django 4.1.7 on 2023-07-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryJ', '0006_alter_website_book_title_page_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='image_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
