# Generated by Django 4.1.7 on 2023-07-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryJ', '0007_website_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='book_description_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
