# Generated by Django 4.1.7 on 2023-07-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryJ', '0009_website_book_author_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='book_tags_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
