# Generated by Django 4.1.7 on 2023-07-23 02:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryJ', '0011_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
