# Generated by Django 4.1.7 on 2023-07-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryJ', '0012_book_description_book_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='art_link',
            new_name='first_chapter_link',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_link',
            new_name='image_link',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_title',
            new_name='last_chapter_link',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='last_page_link',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='art_path',
            new_name='book_content_path',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='content_path',
            new_name='book_image_path',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='image_link',
            new_name='icon_link',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='next_book_page_link_path',
            new_name='next_chapter_link_path',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='previous_book_page_link_path',
            new_name='previous_chapter_link_path',
        ),
    ]
