# Generated by Django 4.1.7 on 2023-08-14 21:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryJ', '0015_remove_book_last_chapter_link_book_last_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content_en',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), blank=True, default=list, size=None),
        ),
    ]
